name: 🚀 Deploy do main
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy de main
    runs-on: ubuntu-24.04
    steps:
      - name: 🚚 Baixando o código
        uses: actions/checkout@v4

      - name: Copiando arquivos para o servidor
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }} 
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: /var/www/html/portfolio

